name: library_app_4_oct
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^23.1.36
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  provider: ^6.0.5
  file_picker: ^6.0.0
  shared_preferences: ^2.2.2
  sqflite_common_ffi: ^2.3.3+1
  flutter_staggered_animations: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true